AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function to generate firmware download link with expiry and store it in DynamoDB with TTL

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction/
      Handler: helloworld.App::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: FirmwareVersionTable
        - DynamoDBWritePolicy:
            TableName: PresignedLinkTable
        - S3ReadPolicy:
            BucketName: firmware-1bucket
      Environment:
        Variables:
          TABLE_NAME: FirmwareVersionTable
          LINK_TABLE_NAME: PresignedLinkTable
          BUCKET_NAME: firmware-1bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: post

  FirmwareVersionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FirmwareVersionTable
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  PresignedLinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PresignedLinkTable
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: PAY_PER_REQUEST

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for HelloWorld function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
